/**
 * Created by YepezHinostroza on 6/6/2017.
 */
public enum Categoria {
    FISICA,MATEMATICA,COMPUTACION,AERONAUTICA,CIVIL,GEOLOGIA,BIOMEDICA,ELECTRONICA,MECANICA,AMBIENTAL,MEMES,INDUSTRIAL,LEGAL,QUIMICA,MUSICA


}
