/**
 * Created by YepezHinostroza on 25/6/2017.
 */
public enum EstadoVentanas {
    INICIAL, BIBLIOTECARIO,LOGOUT,LOGIN,AFILIADOS,AGREGARAFILIADO,VERAFILIADOS,BORRARAFILIADO,SUSPENDER,MODDATOS,MODPERMISOS,EJEMPLARES,AGREGAREJEMPLARES,
    AGREGARLIBRO,AGREGARREVISTA,AGREGARAUDIOV,AGREGARTESIS,VEREJEMPLARES,BORRAREJEMPLAR,DARBAJA,MODFECHA,PRESTAMOS,PRESTAMO,DEVOLUCION,CONSULTAS,CONSULTAITEM, CONSULTACATEGORIA,RESULTADOITEM, RESULTADOCATEGORIA
}
